[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tm1_bedrock_py"
version = "0.1.0"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A python modul for TM1 Bedrock."
readme = "README.md"
requires-python = ">=3.7"
keywords=["TM1", "IBM Cognos TM1", "Planning Analytics", "PA", "Cognos"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "TM1py",
    "mdxpy",
    "pandas",
    "json_logging",
    "sqlalchemy"
]

[project.optional-dependencies]
dev = ["build", "pytest", "parametrize_from_file", "apache_airflow", "airflow_provider_tm1"]

[tool.setuptools]
packages = ["tm1_bedrock_py"]