from TM1_bedrock_py.calc import (
    Model,
    StaticMetadataProvider,
    build_static_cube_metadata,
)
from tests.mock_tm1_service import MockTM1Service


def _string_sales_metadata_provider():
    return StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={
                    "First Name": "String",
                    "Last Name": "String",
                    "Full Name": "String",
                    "Revenue": "Numeric",
                },
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
            ),
            "FX Rates": build_static_cube_metadata(
                "FX Rates",
                ["Version", "Currency", "Measure"],
                measure_element_types={"Label": "String"},
            ),
        }
    )


def test_compile_deploys_string_concat_with_same_cube_traceback_feeders():
    provider = _string_sales_metadata_provider()
    tm1_service = MockTM1Service()
    model = Model(metadata_provider=provider, tm1=tm1_service)
    sales = model.cube("Sales")

    sales["Full Name"] = (
        sales["First Name"].concat(" ").concat(sales["Last Name"])
    ).native(scope="string", feeder_mode="safe_union")

    explanation = model.explain("Sales:Full Name")
    preview = model.compile(dry_run=True)

    assert explanation["backend"] == "native-rule backend"
    assert explanation["feeder_strategy"] == "same_cube_traceback"
    assert preview.rules["Sales"] == (
        "['Measure':'Measure':'Full Name'] = S: "
        "((['Measure':'Measure':'First Name'] | ' ') | ['Measure':'Measure':'Last Name']);"
    )
    assert preview.feeders["Sales"] == (
        "['Measure':'Measure':'First Name'] => ['Measure':'Measure':'Full Name'];\n"
        "['Measure':'Measure':'Last Name'] => ['Measure':'Measure':'Full Name'];"
    )
    assert preview.manifest["Sales:Full Name"]["rule_area"] == "string"
    assert preview.manifest["Sales:Full Name"]["artifact"]["preview_only"] is False

    deployment = model.compile(dry_run=False)
    assert deployment.errors == []
    assert deployment.deployment["Sales"]["deployed"] is True
    assert deployment.deployment["Sales"]["check_rules_status"] == 200
    assert tm1_service.cubes.get("Sales").rules.text == (
        "# Generated by TM1_bedrock_py calc Phase 2 compiler\n"
        "# Cube: Sales\n"
        "FEEDSTRINGS;\n"
        "\n"
        "SKIPCHECK;\n"
        "\n"
        "['Measure':'Measure':'Full Name'] = S: "
        "((['Measure':'Measure':'First Name'] | ' ') | ['Measure':'Measure':'Last Name']);\n"
        "\n"
        "FEEDERS;\n"
        "['Measure':'Measure':'First Name'] => ['Measure':'Measure':'Full Name'];\n"
        "['Measure':'Measure':'Last Name'] => ['Measure':'Measure':'Full Name'];\n"
    )


def test_compile_lowers_string_upper_and_where_for_s_scope():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={
                    "Status": "String",
                    "Status Upper": "String",
                },
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
            ),
        }
    )
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Status Upper"] = sales["Status"].upper().where(sales["Status"] != "").native(scope="string")

    explanation = model.explain("Sales:Status Upper")
    preview = model.compile(dry_run=True)

    assert explanation["backend"] == "native-rule backend"
    assert preview.rules["Sales"] == (
        "['Measure':'Measure':'Status Upper'] = S: "
        "IF((['Measure':'Measure':'Status'] <> ''), UPPER(['Measure':'Measure':'Status']), STET);"
    )


def test_compile_lowers_string_case_for_s_scope():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={
                    "Status": "String",
                    "Status Label": "String",
                },
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
            ),
        }
    )
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Status Label"] = model.case(
        (sales["Status"] != "Open", sales["Status"]),
        default="Open",
    ).native(scope="string")

    explanation = model.explain("Sales:Status Label")
    assert explanation["backend"] == "native-rule backend"
    assert explanation["feeder_strategy"] == "same_cube_traceback"


def test_compile_rejects_string_target_when_measure_is_not_string_typed():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                measure_element_types={"Revenue": "Numeric", "Status Upper": "Numeric"},
            ),
        }
    )
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Status Upper"] = sales["Revenue"].native(scope="string")

    explanation = model.explain("Sales:Status Upper")
    assert explanation["backend"] == "Python materialization backend"
    assert "String element type" in explanation["rationale"]


def test_compile_rejects_string_formula_referencing_numeric_measure():
    provider = _string_sales_metadata_provider()
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Full Name"] = (sales["First Name"] + sales["Revenue"]).native(scope="string")

    explanation = model.explain("Sales:Full Name")
    assert explanation["backend"] == "Python materialization backend"
    assert "Revenue" in explanation["rationale"]
    assert "String element type" in explanation["rationale"]


def test_compile_previews_cross_cube_align_inside_string_scope_but_stays_preview_only_without_metadata():
    """Cross-cube S: align(...) is no longer rejected outright -- it goes through the same
    metadata-proven feeder-origin gate as N:, so without leaf/hierarchy metadata it compiles
    natively but stays preview-only rather than falling back to Python or being rejected."""
    provider = _string_sales_metadata_provider()
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")
    fx = model.cube("FX Rates")

    sales["First Name"] = fx["Label"].align(Currency="USD").native(scope="string")

    explanation = model.explain("Sales:First Name")
    assert explanation["backend"] == "native-rule backend"
    assert explanation["feeder_strategy"] == "preview_only_cross_cube"
    assert explanation["native_eligibility"]["status"] == "metadata_incomplete"


def test_compile_deploys_cross_cube_align_inside_string_scope_when_target_leaf_scope_is_proven():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={"First Name": "String"},
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
                dimension_leaf_elements={"Region": ["East", "West"]},
            ),
            "FX Rates": build_static_cube_metadata(
                "FX Rates",
                ["Version", "Currency", "Measure"],
                default_hierarchies={"Version": "Version", "Currency": "Currency", "Measure": "Measure"},
                measure_element_types={"Label": "String"},
                dimension_hierarchies={"Version": ["Version"], "Currency": ["Currency"], "Measure": ["Measure"]},
                dimension_leaf_elements={"Currency": ["USD"]},
            ),
        }
    )
    model = Model(tm1=MockTM1Service(), metadata_provider=provider)
    sales = model.cube("Sales")
    fx = model.cube("FX Rates")

    sales["First Name"] = fx["Label"].align(Currency="USD").native(scope="string")

    explanation = model.explain("Sales:First Name")
    preview = model.compile(dry_run=True)

    assert explanation["feeder_strategy"] == "cross_cube_source_lookup"
    assert preview.manifest["Sales:First Name"]["artifact"]["preview_only"] is False
    assert preview.rules["Sales"] == (
        "['Measure':'Measure':'First Name'] = S: DB('FX Rates', !Version, "
        "'Currency':'Currency':'USD', 'Measure':'Measure':'Label');"
    )
    assert preview.feeders["FX Rates"] == (
        "[!Version, 'Currency':'Currency':'USD', 'Measure':'Measure':'Label'] => "
        "DB('Sales', !Version, 'Region':'Region':'East', 'Measure':'Measure':'First Name'), "
        "DB('Sales', !Version, 'Region':'Region':'West', 'Measure':'Measure':'First Name');"
    )

    deployment = model.compile(dry_run=False)
    assert deployment.errors == []
    assert deployment.deployment["Sales"]["deployed"] is True
    assert deployment.deployment["FX Rates"]["deployed"] is True
    assert model.tm1.cubes.get("Sales").rules.text.startswith(
        "# Generated by TM1_bedrock_py calc Phase 2 compiler\n"
        "# Cube: Sales\n"
        "FEEDSTRINGS;\n"
        "\n"
        "SKIPCHECK;\n"
    )


def test_compile_rejects_time_intelligence_methods_inside_string_scope():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Month", "Measure"],
                measure_element_types={"Status": "String"},
                dimension_leaf_elements={"Month": ["1", "2", "3"]},
            ),
        }
    )
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Status"] = sales["Status"].shift(Month=-1).native(scope="string")

    explanation = model.explain("Sales:Status")
    assert explanation["backend"] == "Python materialization backend"
    assert "does not support shift(...)" in explanation["rationale"]


def test_compile_deploys_string_target_referencing_numeric_measure_via_to_string():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={"Revenue": "Numeric", "Revenue Label": "String"},
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
            ),
        }
    )
    model = Model(metadata_provider=provider, tm1=MockTM1Service())
    sales = model.cube("Sales")

    sales["Revenue Label"] = sales["Revenue"].to_string(10, 2).native(scope="string")

    explanation = model.explain("Sales:Revenue Label")
    preview = model.compile(dry_run=True)

    assert explanation["backend"] == "native-rule backend"
    assert explanation["feeder_strategy"] == "same_cube_traceback"
    assert preview.rules["Sales"] == (
        "['Measure':'Measure':'Revenue Label'] = S: STR(['Measure':'Measure':'Revenue'], 10, 2);"
    )
    assert preview.feeders["Sales"] == (
        "['Measure':'Measure':'Revenue'] => ['Measure':'Measure':'Revenue Label'];"
    )
    assert preview.manifest["Sales:Revenue Label"]["artifact"]["preview_only"] is False

    deployment = model.compile(dry_run=False)
    assert deployment.errors == []
    assert deployment.deployment["Sales"]["deployed"] is True


def test_compile_deploys_numeric_target_referencing_string_measure_via_to_number():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                default_hierarchies={"Version": "Version", "Region": "Region", "Measure": "Measure"},
                measure_element_types={"Revenue Text": "String", "Revenue": "Numeric"},
                dimension_hierarchies={"Version": ["Version"], "Region": ["Region"], "Measure": ["Measure"]},
            ),
        }
    )
    model = Model(metadata_provider=provider, tm1=MockTM1Service())
    sales = model.cube("Sales")

    sales["Revenue"] = sales["Revenue Text"].to_number()

    explanation = model.explain("Sales:Revenue")
    preview = model.compile(dry_run=True)

    assert explanation["backend"] == "native-rule backend"
    assert preview.rules["Sales"] == (
        "['Measure':'Measure':'Revenue'] = N: NUMBR(['Measure':'Measure':'Revenue Text']);"
    )
    assert preview.manifest["Sales:Revenue"]["artifact"]["preview_only"] is False

    deployment = model.compile(dry_run=False)
    assert deployment.errors == []
    assert deployment.deployment["Sales"]["deployed"] is True


def test_compile_rejects_to_number_applied_to_non_measure_expression():
    provider = StaticMetadataProvider(
        {
            "Sales": build_static_cube_metadata(
                "Sales",
                ["Version", "Region", "Measure"],
                measure_element_types={"A": "String", "B": "String", "Revenue": "Numeric"},
            ),
        }
    )
    model = Model(metadata_provider=provider)
    sales = model.cube("Sales")

    sales["Revenue"] = (sales["A"].concat(sales["B"])).to_number()

    explanation = model.explain("Sales:Revenue")
    assert explanation["backend"] == "Python materialization backend"
    assert "only supported directly on a measure reference" in explanation["rationale"]


def test_register_formula_rejects_unsupported_scope():
    model = Model()
    sales = model.cube("Sales")

    try:
        sales["Status"] = sales["Status"].native(scope="X")
    except ValueError as error:
        assert "Unsupported rule-area scope" in str(error)
    else:
        raise AssertionError("Expected ValueError for unsupported scope")
