version: '3.8'

services:
  mssql:
    build: .
    container_name: mssql
    ports:
      - "5835:1433"
    environment:
      SA_PASSWORD: "niw9-ueI!ZeL5"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    healthcheck:
      test: [ "CMD-SHELL", "pidof sqlservr || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    volumes:
      - ./init-db.sql:/opt/mssql/data/init-db.sql
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 10 && 
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'niw9-ueI!ZeL5' -i /opt/mssql/data/init-db.sql -C &&
        wait
