# Define reusable parts
default_elements: &default_elements
  NumberOfElements: 10000
  ElementPrefix: "P"
  ElementLength: 8
  Method: "enumerate"

default_levels: &default_levels
  - name: "level000"
    constant_content: "All Product"
  - name: "level001"
    content_template:
      Prefix: "ProductGroup"
      Length: 2
      Method: "enumerate"
  - name: "level002"
    content_template:
      Prefix: "ProductSubCategory"
      Length: 2
      Method: "enumerate"

default_attributes: &default_attributes
  - "AccountType:s"
  - "Size:s"

# Define the main default using the parts
default: &defaults
  dimension_name: "testbenchProduct"
  df_template:
    elements: *default_elements
    levels: *default_levels
    attributes: *default_attributes
#Defind Tm1 bedrock test cases
bedrock_test_10000:
  <<: *defaults
  df_template:
    elements:
      <<: *default_elements
      NumberOfElements: 100
    levels: *default_levels
    attributes: *default_attributes
bedrock_test_50000:
  <<: *defaults
  df_template:
    elements:
      <<: *default_elements
      NumberOfElements: 100
    levels: *default_levels
    attributes: *default_attributes
bedrock_test_100000:
  <<: *defaults
  df_template:
    elements:
      <<: *default_elements
      NumberOfElements: 1000
    levels: *default_levels
    attributes: *default_attributes
bedrock_test_250000:
  <<: *defaults
  df_template:
    elements:
      <<: *default_elements
      NumberOfElements: 1000
    levels: *default_levels
    attributes: *default_attributes
bedrock_test_500000:
  <<: *defaults
  df_template:
    elements:
      <<: *default_elements
      NumberOfElements: 1000
    levels: *default_levels
    attributes: *default_attributes
bedrock_test_1000000:
  <<: *defaults
bedrock_test_5000000:
  <<: *defaults
bedrock_test_10000000:
  <<: *defaults